apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-ngnix
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-to-ngnix

  ports:
  - port: 3333
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-to-ngnix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-web-to-ngnix
  
  template:
    metadata:
      labels:
        app: k8s-web-to-ngnix
    
    spec:
      containers:
      - name: k8s-web-to-ngnix
        image: vikendu/k8s-web-to-ngnix
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
